# Generated by Django 3.0.10 on 2020-11-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_date_of_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(default='no biography', help_text='Enter a biography', max_length=1000),
        ),
    ]
